name: mask_rcnn_metal-env
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - numpy=1.23.5
  - pillow=9.4.0
  - pytorch-nightly
  - torchvision=0.14.1
  - matplotlib=3.7.1
  - jupyter=1.0.0
  - pip:
    - pycocotools==2.0.6
    - albumentations==1.3.0
    - opencv-python==4.7.0.72
    - tensorboard==2.12.0
    - tqdm==4.65.0
    - pyyaml==6.0