# Detectron2 evaluation configuration

# Model configuration
model_zoo_config: "COCO-Detection/cascade_rcnn_X_101_32x8d_FPN_3x.yaml"

# Dataset paths
datasets:
  train_json: "data/annotations/coco100/train/_annotations.coco.json"
  train_img_dir: "data/annotations/coco100/train"
  val_json: "data/annotations/coco100/val/_annotations.coco.json"
  val_img_dir: "data/annotations/coco100/val"
  test_json: "data/annotations/coco100/test/_annotations.coco.json"
  test_img_dir: "data/annotations/coco100/test"

# Dataloader configuration
dataloader:
  num_workers: 4

# Input configuration (added to fix the error)
INPUT:
  MIN_SIZE_TRAIN: [640, 672, 704, 736, 768, 800]  # List of integers for random scaling during training
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

# ROI heads configuration
roi_heads:
  num_classes: 2  # Updated to match the 2 classes found in annotations (0: leaves, 1: Leaf)

# Training behavior configuration
training:
  ignore_shape_mismatch: true  # Set to true to ignore weight shape mismatches on pre-trained models

# Output directory for evaluation results
output_dir: "data/processed/detectron2"
model_path: "checkpoints/detectron2/5-2/model_final.pth"
metrics_output: "metrics.json" 